# Generated by Django 2.2.7 on 2019-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_chatmodel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
