# Generated by Django 2.2.7 on 2019-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_chatmodel_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
