# Generated by Django 3.0.8 on 2020-07-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20200709_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Facturas',
        ),
    ]
