# Generated by Django 3.0.8 on 2020-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20200709_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=1000)),
                ('entidades', models.CharField(max_length=1000)),
            ],
        ),
    ]
